version: '3'

volumes:
    vol_wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/hyna/data/wordpress
    vol_database:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/hyna/data/mariadb
services:
    mariadb:
        build:
            context: ./requirements/mariadb
            dockerfile: ./Dockerfile
        container_name: mariadb
        hostname: mariadb
        volumes:
            - vol_database:/var/lib/mysql
        restart: always
        expose: #port와 expose 둘 다 같은 기능이나, expose는 같은 호스트 내의 컨테이너만 포트 번호로 접근 가능함
            - "3306"
        networks:
            - intra
    nginx:
        env_file:
            - ./.env
        build:
            context: ./requirements/nginx
            dockerfile: ./Dockerfile
        container_name: nginx
        hostname: nginx
        volumes:
            - vol_wordpress:/var/www/html
        restart: always
        ports:
            - 443:443
        networks:
            - intra
        tty: true
    wordpress:
        env_file:
            - ./.env
        build:
            context: ./requirements/wordpress
            dockerfile: ./Dockerfile
        container_name: wordpress
        hostname: wordpress
        volumes:
            - vol_wordpress:/var/www/html
        restart: always
        expose:
            - "9000"
        networks:
            - intra
        tty: true
networks:
    intra:
        driver: bridge